### ISSUE TITLE
Define endpoint for installation statistics

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/marketplace-rest-api-specs#10]
Information about installation statistics should be provided and stored by this endpoint to maintain current functionality.

**Comment by briandealwis** [comment]
A requested in [bug 526508](https://bugs.eclipse.org/bugs/show_bug.cgi?id=526508) it would be very useful for plugin developers to be able to slice and dice summaries by versions of the Platform used, by OS, and JVM.  Being able to map requests to countries would be gravy.  This would allow plugin developers to decide questions like:

  - can I require Java 8? (how many installations in the last 3 months are using JRE < 1.8?)
  - should I continue to support 4.5/Mars?
  - should I localize my content?

**Comment by autumnfound** [comment]
Hey Brian,

Chris and I talked over implementation, and we are looking at including locale, country, OS, eclipseVersion, and javaVersion in our installation log table. We plan on implementing some filters that will allow users to request more intricate results than the default set of metrics. I'll be adding this to the spec in the next day or so for others to familiarize them selves with it.
