### ISSUE TITLE
Generate static documentation website 

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/marketplace-rest-api-specs#4]
@autumnfound is recommending that we leverage https://github.com/sourcey/spectacle

**Comment by tedepstein** [comment]
@chrisguindon , @autumnfound , I would also take a good look at [ReDoc](https://redoc.ly/). GitHub repo is at [Redocly/redoc](https://github.com/Redocly/redoc).

**Comment by chrisguindon** [comment]
@tedepstein I took a look at Redoc and we will start with your suggestion!

I will use https://github.com/Redocly/create-openapi-repo to update the repo.

**Comment by chrisguindon** [comment]
My PR is almost ready. 

I will the model folder since the tool that you are suggesting is creating a new spec/openapi.yaml file with the content of marketplace-rest-api-specs/models/Eclipse Marketplace API Specification.yaml

I am also removing the gentargets folder as I don't think theses are needed.

**Comment by tedepstein** [comment]
@chrisguindon , nice!

We plan to add a ReDoc code generator to API Studio in the near future. Maybe we can also implement publishing to GitHub pages from there, so you can manage the full documentation publishing process from API Studio. Unfortunately, I can't promise that this will be ready in time for the initial release of the Eclipse Marketplace v2 API, but maybe for next time.

**Comment by chrisguindon** [comment]
We now have a website for hosting our documentation!
https://eclipsefdn.github.io/marketplace-rest-api-specs/

Thank @tedepstein for making the suggestion.
